version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server

  # chirpstack-gateway-bridge:
  #   image: chirpstack/chirpstack-gateway-bridge:3
  #   ports:
  #     - 1700:1700/udp
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge

  # chirpstack-geolocation-server:
  #   image: chirpstack/chirpstack-geolocation-server:3
  #   volumes:
  #     - ./configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  datadog:
    links:
     - redis # Connect the Datadog Agent container to the Redis container
     - postgresql
    image: gcr.io/datadoghq/agent:latest
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  postgresqldata:
  redisdata:
